{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import re\n",
    "import csv\n",
    "from bs4 import BeautifulSoup\n",
    "from urllib.request import Request, urlopen\n",
    "\n",
    "# The website we are scraping from\n",
    "base_url = \"https://stackoverflow.com/questions?page={}\"\n",
    "\n",
    "# A user-agent to make our request look like it’s coming from a real browser\n",
    "headers = {'User-Agent': 'Mozilla/5.0'}\n",
    "\n",
    "# Counters for each year\n",
    "year_count = {\"2024\": 0, \"2023\": 0, \"2022\": 0}\n",
    "max_questions = {\"2024\": 10000, \"2023\": 5000, \"2022\": 5000}\n",
    "\n",
    "# Open a CSV file to store our results\n",
    "with open(\"stackoverflow_questions.csv\", \"w\", newline=\"\", encoding=\"utf-8\") as file:\n",
    "    writer = csv.writer(file)\n",
    "\n",
    "    # Write the column names at the top of the file\n",
    "    writer.writerow([\"Question Title\", \"Year\", \"Relative Time\", \"Language\"])  \n",
    "\n",
    "    # We will go through multiple pages on Stack Overflow\n",
    "    for page in range(10000,21000):  \n",
    "        try:\n",
    "            # Request the webpage\n",
    "            request = Request(base_url.format(page), headers=headers)\n",
    "            response = urlopen(request)\n",
    "\n",
    "            # Parse the webpage using BeautifulSoup\n",
    "            soup = BeautifulSoup(response, \"html.parser\")\n",
    "        except:\n",
    "            # If something goes wrong, just move to the next page\n",
    "            continue  \n",
    "\n",
    "        # Find all the questions on this page\n",
    "        questions = soup.find_all(\"div\", class_=\"s-post-summary\")\n",
    "\n",
    "        # Go through each question one by one\n",
    "        for question in questions:\n",
    "            # Extract the question title\n",
    "            title_element = question.find(\"h3\")\n",
    "            question_title = title_element.text.strip() if title_element else \"Unknown\"\n",
    "\n",
    "            # Find all the programming languages (tags) related to this question\n",
    "            tags = question.find_all(\"a\", class_=\"post-tag\")\n",
    "\n",
    "            # Convert them into a list of text\n",
    "            tag_list = [tag.text.strip() for tag in tags]\n",
    "\n",
    "            # Find when this question was posted\n",
    "            time_element = question.find(\"span\", class_=\"relativetime\")\n",
    "\n",
    "            # If we find the time, use it; otherwise, mark it as \"Unknown\"\n",
    "            relative_time = time_element[\"title\"] if time_element else \"Unknown\"\n",
    "\n",
    "            # Extract the year from the date\n",
    "            match = re.search(r\"(\\d{4})\", relative_time)\n",
    "\n",
    "            # If we find a valid year, use it; otherwise, mark it as \"Unknown\"\n",
    "            year = match.group(1) if match else \"Unknown\"\n",
    "\n",
    "            # Check if we need more questions from this year\n",
    "            if year in max_questions and year_count[year] < max_questions[year]:\n",
    "                # If the question has multiple tags, write a separate row for each tag\n",
    "                for tag in tag_list or [\"Unknown\"]:\n",
    "                    writer.writerow([question_title, year, relative_time, tag])\n",
    "                \n",
    "                # Update the count\n",
    "                year_count[year] += 1\n",
    "\n",
    "            # Stop if we have collected enough questions for all years\n",
    "            if all(year_count[y] >= max_questions[y] for y in max_questions):\n",
    "                print(\"✅ Scraping is done! The data is saved in 'stackoverflow_questions.csv'.\")\n",
    "                exit()\n",
    "\n",
    "print(\"✅ Scraping is done! The data is saved in 'final_data_stackoverflow_questions.csv'.\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
